"""hospitals and email verification

Revision ID: 9a2b6acf50c5
Revises: bf1a476642d6
Create Date: 2026-10-04 10:36:11.780509

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a2b6acf50c5"
down_revision: str | Sequence[str] | None = "bf1a476642d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hospitals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("contact_name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("contact_phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_verification",
                "pending_review",
                "active",
                "rejected",
                "suspended",
                name="hospitalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hospitals")),
    )
    op.create_table(
        "email_verifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_email_verifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_verifications")),
    )
    op.create_index(
        op.f("ix_email_verifications_user_id"), "email_verifications", ["user_id"], unique=False
    )
    op.add_column(
        "users", sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_unique_constraint(op.f("uq_users_email"), "users", ["email"])
    op.create_foreign_key(
        op.f("fk_users_hospital_id_hospitals"), "users", "hospitals", ["hospital_id"], ["id"]
    )
    # ### end Alembic commands ###

    # Block Supabase's auto-generated REST API from these tables (see users migration).
    op.execute("ALTER TABLE hospitals ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE email_verifications ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_hospital_id_hospitals"), "users", type_="foreignkey")
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.drop_column("users", "email_verified_at")
    op.drop_index(op.f("ix_email_verifications_user_id"), table_name="email_verifications")
    op.drop_table("email_verifications")
    op.drop_table("hospitals")
    # ### end Alembic commands ###
