"""bind verification codes to registration

Revision ID: 1187b6989b93
Revises: 9a2b6acf50c5
Create Date: 2026-10-08 20:56:06.994566

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1187b6989b93"
down_revision: str | Sequence[str] | None = "9a2b6acf50c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "email_verifications",
        sa.Column(
            "registration_token_hash",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###
    # Existing rows got '' (matches no token, so old pending codes stop working); new rows always
    # set a value, so drop the default again.
    op.alter_column("email_verifications", "registration_token_hash", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_verifications", "registration_token_hash")
    # ### end Alembic commands ###
